---
- hosts: 192.168.1.215
  become: True
  become_user: root

  vars:
    docker_username: "{{ usr }}"
    docker_password: "{{ pass }}"
    docker_image: maven_war:1.0
    docker_container_name: maven_war

  tasks:
    - name: Display a debug message
      debug:
        msg: docker_username

    - name: Display a debug message
      debug:
        msg: docker_password        
