---
- hosts: linuxclient1
  become: True
  become_user: root

  vars:
    docker_username: your-docker-username
    docker_password: your-docker-password
    docker_image: your-docker-image
    docker_container_name: your-container-name

  tasks:
    - name: Install yum-utils (use the yum module)
      yum:
        name: yum-utils
        state: present    

    - name: Download Docker repository file using the get_url
      shell: sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo    

    - name: Install Docker packages (engine) using yum module, reference https://docs.docker.com/engine/install/centos/#installation-methods
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present    

    - name: Start Docker service using the systemd module
      systemd:
        name: docker
        state: started
        enabled: yes    
        
    - name: log into docker hub registry using the docker_login module
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"    

    - name: Pull image and create the container using docker_container
      docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ docker_image }}"
        state: started
