---
- hosts: linuxclient1
  become: True
  become_user: root

  vars:
    docker_username: "{{ docker_username }}"
    docker_password: "{{ docker_password }}"
    docker_image: maven_war:1.0
    docker_container_name: maven_war

  tasks:
    - name: Display a debug message
      debug:
        msg: "This is a debug message"
