---
- hosts: 192.168.1.215
  become: True
  become_user: root

  tasks:
    - name: Install yum-utils (use the yum module)
      yum:
        name: yum-utils
        state: present    

    - name: Download Docker repository file using the get_url
      shell: sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo    

    - name: Install Docker packages (engine) using yum module, reference https://docs.docker.com/engine/install/centos/#installation-methods
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - epel-release
          - python-pip
        state: present    
        
    - name: Start Docker service using the systemd module
      systemd:
        name: docker
        state: started
        enabled: yes    

    - name: Upgrade pip3
      command: pip install --upgrade pip

    - name: Install docker-py
      pip:
        name: docker-py

    - name: pull docker image    
      docker_image:
        name: imputed5/maven_war:1.0
        source: pull
          
    - name: create the container using docker_container
      docker_container:
        name: maven_war
        image: imputed5/maven_war:1.0
        auto_remove: true        
        state: started
        ports:
         - "8080:8080"
